version: '3.4'
services:
  deploy:
    build: ./
    ports:
     - "7777:7777"
    image: "devclubiitd/deploy:${TAG:-v1.0}"
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - type: volume
        source: builder
        target: /scratch
      - type: volume
        source: docker_conf
        target: /root/.docker
        #read_only: true
      - type: bind
        source: ./ignore/keys
        target: /keys
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /etc/nginx
        target: /etc/nginx
    labels:
      - "in.devclub=Deploy Container"
    logging:
      options:
        max-size: '20m'
        max-file: '10'
      driver: json-file
    restart: unless-stopped
    networks:
      - "internal"
volumes:
    builder:
      labels:
          - "in.devclub=builder volume for deploy bot"
    docker_conf:
      labels:
          - "in.devclub=configuration volume for deploy bot"
networks:
  internal:
